name: Scrape de datos baecobici

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/12 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Get data
      run: |-
        curl 'https://logos.tembici.com.br/ecobici-production/gbfs/station_status.json' | jq '.data.stations |= sort_by((.station_id | capture("station-(?<num>\\d+)").num) | tonumber)' > estaciones.json
        cat estaciones.json | jq 'del(.last_updated) | .data.stations |= map(del(.last_reported, .station_information))' > estaciones_clean.json
    - name: Commit & push if changed
      run: |-
        date=$(date)
        git config user.name "Automatic"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Cambios"|| exit 0
        git push
