name: Scrape de datos baecobici

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '12 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Get data
      run: |-
        curl 'https://logos.tembici.com.br/ecobici-production/gbfs/station_status.json' \
        -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0' \
        -H 'Accept: application/json, text/plain, */*' \
        -H 'Accept-Language: en,en-US' \
        -H 'Accept-Encoding: gzip, deflate, br' \
        -H 'Origin: https://baecobici.com.ar' \ 
        -H 'Connection: keep-alive' \
        -H 'Referer: https://baecobici.com.ar/' \
        -H 'Sec-Fetch-Dest: empty' \
        -H 'Sec-Fetch-Mode: cors' \
        -H 'Sec-Fetch-Site: cross-site' \
        -H 'Sec-GPC: 1' \
        --compressed | jq '.data.stations |= sort_by((.station_id | capture("station-(?<num>\\d+)").num) | tonumber)' > estaciones.json
    - name: Commit & push if changed
      run: |-
        date=$(date)
        git config user.name "Automatic"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Cambios"|| exit 0
        git push
